---
abstract: 'Interface to the Fake Metro Map.'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  Encode: 0
  English: 0
  ExtUtils::MakeMaker: 6.36
  File::Object: 0.08
  Test::More: 0
  Test::NoWarnings: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.21'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Map-Tube-Fake
no_index:
  directory:
    - examples
    - inc
    - share
    - t
requires:
  File::Share: 0
  Map::Tube: '2.41'
  Moo: 0
  namespace::clean: 0
  perl: 5.8.0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Map-Tube-Fake
  homepage: https://github.com/tupinek/Map-Tube-Fake
  license: http://opensource.org/licenses/artistic-license-2.0.php
  repository: git://github.com/tupinek/Map-Tube-Fake
version: '0.03'
